
sudo: required

install: true

services:
  - docker

language: node_js

node_js:
  - "lts/carbon"

cache:
  directories:
    - node_modules

before_install:
  - npm i -g npm@latest
  - yarn
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
  - npm run lint
  - npm run test:cov

after_success:
  - docker --version
  - docker build -t kerrokantasi-ui .
  - docker tag kerrokantasi-ui roninen/kerrokantasi-ui:latest
  - docker push roninen/kerrokantasi-ui:latest
