
sudo: required

install: true

services:
  - docker

language: node_js

node_js:
  - "lts/*"
  - "node"

cache:
  directories:
    - node_modules

before_install:
  - npm i -g npm@latest
  - yarn

script:
  - npm run lint
  - npm run test:cov
  - ./docker_test.sh

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - env
  - ./deploy.sh

