
sudo: required

install: true

env:
    global:
        - COMMIT=${TRAVIS_COMMIT::6}

services:
  - docker

language: node_js

node_js:
  - "lts/carbon"

cache:
  directories:
    - node_modules

before_install:
  - npm i -g npm@latest
  - yarn
  - docker --version
  - docker build -t kerrokantasi-ui .

#script:
#  - docker run --rm kerrokantasi-ui /bin/bash -c "npm run lint"
#  - docker run --rm kerrokantasi-ui /bin/bash -c "npm run test:cov"

# remove testing code temporarily for testing build
script:
  - true

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - env
  - ./deploy.sh

